####################################
#    MailCord Configuration File   #
#          Author: NAFU_at         #
#         Version: v1.0            #
####################################
authorization:
  discord:
    guildId: 123456789

  mailServer:
    - address: mail@example.com
      smtp:
        serverAddress: smtp.example.com
        port: 25
        ssl: STARTTLS
        username: username
        password: password
        channel: 123456798
        bypassServerTrust: false
      imap:
        serverAddress: imap.example.com
        port: 143
        ssl: STARTTLS
        username: uername
        password: password
        channel: 123456798
        bypassServerTrust: false

debugMode: false
